title: 'Buku Danardatu'
default_lang: en
author:
  name: 'Danar Datu'
  email: designtopia.id@gmail.com
taxonomies:
  - category
  - tag
metadata:
  'Alaysius Harnowo, ulang tahun ke 70': 'Buku Danardatu'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
